import fs from "node:fs/promises";
import path from "node:path";
import os from "node:os";
import { randomUUID } from "node:crypto";
import { commands, flags } from "./commands.mjs";
import { SyncError } from "./errors.mjs";

const quoted = value => "'" + value.replaceAll("'", "'\\''") + "'";
const specs = action => flags.filter(f => !f.actions || (action ? f.actions.includes(action) : f.key === "dir")).flatMap(f =>
  f.names.map(name => quoted(`(${f.names.join(" ")})${name}[${f.description}]${f.argument ? ":目录:_directories" : ""}`))).join(" \\\n      ");
export function zshCompletion() {
  const cases = commands.filter(c => c.name !== "completion").map(c => `    ${c.name})\n      _arguments ${specs(c.name)}\n      ;;`).join("\n");
  return `#compdef devsync
# Generated by devsync completion zsh. No project or SSH access is required.
_devsync() {
  local context state state_descr line
  typeset -A opt_args
  _arguments -C ${specs()} \\
    '1:命令:->commands' \\
    '*::参数:->arguments'
  case $state in
    commands)
      local -a commands=(
${commands.map(c => "        " + quoted(`${c.name}:${c.description}`)).join("\n")}
      )
      _describe 'devsync 命令' commands
      ;;
    arguments)
      case $line[1] in
${cases}
        completion)
          _arguments -C ${specs("completion")} \\
            '1:补全操作:->completion' \\
            '2:Shell:->shell'
          case $state in
            completion)
              local -a operations=('zsh:输出 zsh 补全脚本' 'install:安装补全' 'uninstall:卸载补全')
              _describe '补全操作' operations
              ;;
            shell)
              if [[ $line[1] == install || $line[1] == uninstall ]]; then
                compadd zsh
              fi
              ;;
          esac
          ;;
      esac
      ;;
  esac
}
if (( $+functions[compdef] )); then
  compdef _devsync devsync
fi
`;
}

const begin = "# >>> devsync completion >>>";
const end = "# <<< devsync completion <<<";
const block = `${begin}
if command -v devsync >/dev/null 2>&1; then
  if ! (( $+functions[compdef] )); then
    autoload -Uz compinit && compinit
  fi
  if (( $+functions[compdef] )); then
    eval "$(devsync completion zsh)"
  fi
fi
${end}`;

export function updateZshrc(original, install) {
  const starts = [...original.matchAll(/^# >>> devsync completion >>>\r?$/gm)];
  const ends = [...original.matchAll(/^# <<< devsync completion <<<\r?$/gm)];
  if (starts.length !== ends.length || starts.length > 1 || (starts.length && starts[0].index >= ends[0].index))
    throw new SyncError("COMPLETION_CONFIG", "devsync 补全标记不完整或重复，请检查 .zshrc 中的 devsync completion 区块。");
  if (!starts.length) return install ? original + "\n" + block + "\n" : original;
  const start = starts[0].index, finish = ends[0].index + ends[0][0].length;
  if (install) return original.slice(0, start) + block + original.slice(finish);
  // Remove only our block and the separator inserted when installing.
  return original.slice(0, start > 0 && original[start - 1] === "\n" ? start - 1 : start) +
    original.slice(original[finish] === "\n" ? finish + 1 : finish);
}

export async function manageCompletion(action, { env = process.env, home = os.homedir() } = {}) {
  const file = path.resolve(env.ZDOTDIR || home, ".zshrc");
  let target = file, original = "", stat;
  try {
    // Follow user-managed dotfile symlinks without replacing the link itself.
    target = await fs.realpath(file);
    stat = await fs.stat(target);
    original = await fs.readFile(target, "utf8");
  } catch (error) {
    if (error.code !== "ENOENT") throw error;
    // A dangling link needs repair, not replacement.
    try { await fs.lstat(file); throw new SyncError("COMPLETION_CONFIG", `配置链接目标不存在：${file}`); }
    catch (linkError) { if (linkError.code !== "ENOENT") throw linkError; }
  }
  const next = updateZshrc(original, action === "install");
  if (next === original) return { changed: false, file, installed: action === "install" };
  await fs.mkdir(path.dirname(target), { recursive: true });
  const temporary = `${target}.devsync-${randomUUID()}.tmp`;
  try {
    await fs.writeFile(temporary, next, { flag: "wx", mode: stat ? stat.mode & 0o777 : 0o600 });
    if (stat) await fs.chmod(temporary, stat.mode & 0o777);
    let latest = "";
    try { latest = await fs.readFile(target, "utf8"); }
    catch (error) { if (error.code !== "ENOENT") throw error; }
    if (latest !== original) throw new SyncError("COMPLETION_CONFIG", "配置文件在安装期间发生变化，请重试。");
    await fs.rename(temporary, target);
  } finally { await fs.rm(temporary, { force: true }); }
  return { changed: true, file, installed: action === "install" };
}

export const completionHelp = `用法：
  devsync completion zsh             输出 zsh 补全脚本
  devsync completion install zsh     接入当前用户的 .zshrc
  devsync completion uninstall zsh   移除 devsync 管理的补全配置

遵循 ZDOTDIR；安装和卸载可重复执行。新开终端生效。
每次启动交互式 zsh 时加载当前 devsync 的规则，无需在源码更新后重新安装。
`;

export function parseCompletionArgs(args) {
  const json = args.includes("--json");
  const help = args.includes("--help") || args.includes("-h");
  const rest = args.filter(a => !["--json", "--help", "-h"].includes(a));
  if (!rest.length && help) return { help, json };
  const action = rest.length === 1 && rest[0] === "zsh" ? "generate" : rest.length === 2 && ["install", "uninstall"].includes(rest[0]) && rest[1] === "zsh" ? rest[0] : null;
  if (!action) throw new SyncError("USAGE", "补全命令目前仅支持 zsh。\n" + completionHelp);
  return { action, json, help };
}
export async function runCompletion(args) {
  const options = parseCompletionArgs(args);
  if (options.help) { process.stdout.write(completionHelp); return; }
  if (options.action === "generate") {
    const script = zshCompletion();
    process.stdout.write(options.json ? JSON.stringify({ ok: true, shell: "zsh", script }) + "\n" : script);
    return;
  }
  const result = await manageCompletion(options.action);
  process.stdout.write(options.json ? JSON.stringify({ ok: true, ...result }) + "\n" :
    `${result.installed ? "补全已接入" : "补全配置已移除"}：${result.file}${result.changed ? "" : "（无需修改）"}。\n新开终端生效。\n`);
}
